name: Deploy Angular to AWS EC2

on:
  push:
    branches:
      - master  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências e gerar build do Angular
        working-directory: client
        run: |
          npm install --legacy-peer-deps
          npm run build --prod

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # gillrosas22
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build e Push da imagem Docker
        run: |
          docker build --pull -t gillrosas22/ecommerce:latest ./client
          docker push gillrosas22/ecommerce:latest

      - name: Acessar EC2 via SSH e atualizar Kubernetes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            kubectl set image deployment/frontend frontend=gillrosas22/ecommerce:latest -n app-demo
            kubectl rollout status deployment/frontend -n app-demo
